### ISSUE TITLE
Implement protocol to add custom output to `rust-lightning` channel

### ISSUE THREAD

**Issue by luckysori** [get10101/rust-lightning#2]
This is a preparatory step before we implement a protocol which adds a _DLC_ output to a `rust-lightning` channel.

Vanilla Lightning channels can have outputs that pay to a party directly or HTLCs. Both of those types of outputs are involved in payments. With this ticket we want to be able to add a custom output that is not involved in a Lightning payment. Since DLC outputs will also be orthogonal to Lightning payments, we expect to be able to reuse/expand/rewrite the code written when working on this ticket when implementing the Lightning DLC protocol.

The outcome of this ticket should be adding a passing test to the `lightning::ln::functional_tests` module.

**Comment by holzeis** [comment]
@luckysori are you working on a fork of this https://github.com/lightningdevkit ? I guess we should keep that aligned with https://github.com/itchysats/10101/issues/11

**Comment by bonomat** [comment]
We have a fork here https://github.com/itchysats/rust-lightning

**Comment by bonomat** [comment]
Open todos: 

- [x] ensure that we don't just create money when adding a custom output!
- [x] creating an output should use coins from _both_ parties. This means that we need to define simple custom routing which checks that there is a channel between both nodes (no multihop support) and that there is enough outbound and _inbound_ liquidity.
- [x] removing custom output and give funds to the corresponding parties. 
- [x] make custom outputs persistent
- [x] ~make removing custom output interactive: The counterparty should be able to accept/decline removing an output.~ _EDIT: the maker side will automatically accept any custom output removal for the tournament._
- [x] ~make creating an output interactive: The counterparty should be able to accept/decline adding an output.~ _EDIT: Same as above, the maker will accept adding any custom output for the tournament._
- [x] Add a `output_script` argument to the `add_custom_output` API so that we can eventually use it to pass in a DLC script.
- [ ] ensure the flow:  1. update commit transaction with new custom output , 2. create all CETs, then 3. send around signatures. 
- [x] Make custom output scripts revocable!
- [ ] on-chain redemption: if the channel gets _force_-closed we need to spend the output. This can potentially be done from the outside. But for that we need to know the redeem script. 
- [x] ~channel monitor: we will need to update the monitor for our new [custom ouputs](https://github.com/itchysats/rust-lightning/blob/6dd2329ae6731082bbdd5b09eb84ccf25a65b9c3/lightning/src/ln/channel.rs#L5955)~

**Comment by da-kami** [comment]
Can this ticket be closed? I think it is done in regards to the tournament.

**Comment by luckysori** [comment]
> Can this ticket be closed? I think it is done in regards to the tournament.

Yep!
